---
kind: pipeline
type: docker
name: salut

steps:
- name: hello-world
  image: lowess/preact-cli
  commands:
  - npx preact-cli create delhaiea/preact-hugo test
  - cd test
  - npm i
  - npm run build

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: drone-ci

- name: publish  
  image: plugins/gh-pages
  settings:
    ssh_key:
      from_secret: github_ssh_key
    username:
      from_secret: github_username
    pages_directory: build